name: spendulum
description: "Spendulum: Expense and Income Tracker"
publish_to: "none"

version: 0.1.0-alpha+3

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^3.0.7
  provider: ^6.1.2
  intl: ^0.19.0
  flutter_colorpicker: ^1.1.0
  fl_chart: ^0.66.0
  logger: ^1.4.0
  sqflite: ^2.3.2
  path: ^1.8.3
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.0.15
  percent_indicator: ^4.0.1
  csv: ^5.0.1
  excel: ^2.0.1
  mailer: ^6.2.0
  workmanager: ^0.5.1
  path_provider: ^2.0.15
  flutter_local_notifications: ^18.0.0
  timezone: ^0.9.0
  flutter_timezone: ^3.0.1
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.0.0
  encrypt: ^5.0.3
  url_launcher: ^6.1.14
  package_info_plus: ^4.0.0
  permission_handler: ^11.3.1
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.2
  get_it: ^7.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/images/app_icon.png
    - .env
  uses-material-design: true
