import 'package:flutter/material.dart';

Map<String, String> _currencySymbols = {
  'USD': '\$',
  'EUR': '€',
  'GBP': '£',
  'JPY': '¥',
  'AUD': '\$',
  'CAD': '\$',
  'CHF': 'Fr.',
  'CNY': '¥',
  'HKD': '\$',
  'NZD': '\$',
  'SEK': 'kr',
  'KRW': '₩',
  'INR': '₹',
  'BRL': 'R\$',
  'RUB': '₽',
  'MXN': '\$',
  'ZAR': 'R',
  'TRY': '₺',
  'PLN': 'zł',
  'NOK': 'kr',
  'DKK': 'kr',
  'THB': '฿',
  'MYR': 'RM',
  'PHP': '₱',
  'IDR': 'Rp',
  'VND': '₫',
  'AED': 'د.إ',
  'SAR': 'ر.س',
  'HRK': 'kn',
  'CZK': 'Kč',
  'HUF': 'Ft',
  'ARS': '\$',
  'CLP': '\$',
  'COP': '\$',
  'PEN': 'S/',
  'UYU': '\$U',
  'DOP': 'RD\$',
  'CRC': '₡',
  'PYG': '₲',
  'BOB': 'Bs.',
  'GTQ': 'Q',
  'NIO': 'C\$',
  'HNL': 'L',
  'SVC': '\$',
  'NP': '₨',
  'PKR': '₨',
  'BDT': '৳',
  'LKR': '₨',
  'MMK': 'K',
  'KHR': '៛',
  'LAK': '₭',
  'BND': 'B\$',
  'SGD': '\$',
  'BWP': 'P',
  'NAD': '\$',
  'ZMW': 'ZK',
  'TZS': 'TSh',
  'UGX': 'USh',
  'KES': 'Ksh',
  'ETB': 'Br',
  'GHS': '₵',
  'ZWL': 'Z\$',
  'MWK': 'MK',
  'MZN': 'MT',
  'AOA': 'Kz',
  'CDF': 'FC',
  'SDG': 'SDG',
  'SLL': 'Le',
  'SZL': 'E',
  'LSL': 'L',
  'RWF': 'RF',
  'BIF': 'FBu',
  'GNF': 'FG',
  'XAF': 'FCFA',
  'XOF': 'CFA',
  'XPF': 'CFPF',
  'DJF': 'Fdj',
  'ERN': 'Nfk',
  'GMD': 'D',
  'CVE': '₠',
  'MRO': 'UM',
  'STD': 'Db',
  'KMF': 'CF',
  'SHP': '£',
  'SCR': '₨',
  'SOS': 'Sh.So.',
  'TDC': 'FCFA',
  'XCD': '\$',
  'TMT': 'T',
  'AFN': '؋',
  'AMD': '֏',
  'AZN': '₼',
  'ALL': 'Lek',
  'BAM': 'KM',
  'BGN': 'лв',
  'BYN': 'Br',
  'GEL': '₾',
  'ISK': 'kr',
  'MKD': 'ден',
  'MDL': 'L',
  'RON': 'lei',
  'RSD': 'din',
  'TJS': 'SM',
  'UAH': '₴',
  'UZS': 'лв',
  'XDR': 'SDR'
};

String getCurrencySymbol(String currencyCode) {
  return _currencySymbols[currencyCode] ?? currencyCode;
}

List<String> getCurrencyCodes() {
  return _currencySymbols.keys.toList();
}

IconData getCurrencyIcon(String currency) {
  switch (currency.toUpperCase()) {
    case 'USD':
    case 'JPY':
    case 'AUD':
    case 'CAD':
    case 'CHF':
    case 'CNY':
    case 'HKD':
    case 'NZD':
    case 'SEK':
    case 'KRW':
    case 'BRL':
    case 'RUB':
    case 'MXN':
    case 'ZAR':
    case 'TRY':
    case 'PLN':
    case 'NOK':
    case 'DKK':
    case 'THB':
    case 'MYR':
    case 'PHP':
    case 'IDR':
    case 'VND':
    case 'AED':
    case 'SAR':
    case 'HRK':
    case 'CZK':
    case 'HUF':
    case 'ARS':
    case 'CLP':
    case 'COP':
    case 'PEN':
    case 'UYU':
    case 'DOP':
    case 'CRC':
    case 'PYG':
    case 'BOB':
    case 'GTQ':
    case 'NIO':
    case 'HNL':
    case 'SVC':
    case 'MMK':
    case 'KHR':
    case 'LAK':
    case 'BND':
    case 'SGD':
    case 'BWP':
    case 'NAD':
    case 'ZMW':
    case 'TZS':
    case 'UGX':
    case 'KES':
    case 'ETB':
    case 'GHS':
    case 'ZWL':
    case 'MWK':
    case 'MZN':
    case 'AOA':
    case 'CDF':
    case 'SDG':
    case 'SLL':
    case 'SZL':
    case 'LSL':
    case 'RWF':
    case 'BIF':
    case 'GNF':
    case 'XAF':
    case 'XOF':
    case 'XPF':
    case 'DJF':
    case 'ERN':
    case 'GMD':
    case 'CVE':
    case 'MRO':
    case 'STD':
    case 'KMF':
    case 'SOS':
    case 'TDC':
    case 'XCD':
    case 'TMT':
    case 'AFN':
    case 'AMD':
    case 'AZN':
    case 'ALL':
    case 'BAM':
    case 'BGN':
    case 'BYN':
    case 'GEL':
    case 'ISK':
    case 'MKD':
    case 'MDL':
    case 'RON':
    case 'RSD':
    case 'TJS':
    case 'UAH':
    case 'UZS':
    case 'XDR':
      return Icons.attach_money;

    case 'EUR':
      return Icons.euro;
    case 'GBP':
    case 'SHP':
      return Icons.currency_pound;
    case 'INR':
    case 'NPR':
    case 'PKR':
    case 'BDT':
    case 'LKR':
    case 'SCR':
      return Icons.currency_rupee;

    default:
      return Icons.monetization_on;
  }
}
